import type { DegreeLevel, FundingType, RequirementLevel, SourceReliability } from "@prisma/client";

/**
 * The shape of public/data/scholarships.json — everything a page needs to
 * render a card or a full detail view, with zero further database access
 * (there is no database at runtime). Generated by scripts/export-static-data.ts
 * from the SQLite file, consumed both by build-time Server Components
 * (detail pages, read via fs at build time) and by client-side listing pages
 * (fetched over HTTP at runtime for interactive filtering).
 *
 * Deadlines are shipped as raw ISO strings, not a precomputed status label —
 * `computeDeadlineInfo()` runs again in the browser using the viewer's
 * current clock, so "Closing in 3 days" stays accurate between rebuilds
 * instead of freezing at whatever it was when the site was last generated.
 */
export interface StaticScholarship {
  id: string;
  slug: string;
  title: string;
  provider: string | null;
  university: string | null;
  organization: string | null;
  description: string;
  summary: string | null;

  degreeLevels: DegreeLevel[];
  fundingType: FundingType;

  tuitionCoverage: string | null;
  monthlyStipend: string | null;
  accommodationCovered: boolean | null;
  airfareCovered: boolean | null;
  healthInsuranceCovered: boolean | null;
  applicationFeeCovered: boolean | null;
  otherBenefits: string[];

  minimumEducation: string | null;
  minimumGPA: number | null;
  ageLimit: string | null;
  nationalityRequirements: string | null;
  languageRequirements: string | null;
  ieltsRequired: RequirementLevel;
  toeflRequired: RequirementLevel;
  workExperienceRequired: boolean | null;
  otherEligibility: string | null;
  allNationalitiesEligible: boolean;

  applicationDeadline: string | null; // ISO
  isRolling: boolean;
  openingDate: string | null; // ISO

  primaryCountry: { name: string; code: string; slug: string } | null;
  destinationCity: string | null;
  region: string | null;
  eligibleCountries: { name: string; slug: string }[];
  subjects: { name: string; slug: string }[];

  publishedAt: string | null;
  lastVerifiedAt: string | null;
  sourceReliability: SourceReliability;
  applicationUrl: string;
  officialUrl: string | null;
  isSeed: boolean;
  tags: string[];

  sourceLinks: { sourceName: string; sourceUrl: string; isOfficial: boolean }[];
}

export interface StaticSourceSummary {
  name: string;
  baseUrl: string;
  reliability: SourceReliability;
  lastCrawledAt: string | null;
  totalItemsFound: number;
}

export interface StaticMeta {
  generatedAt: string;
  totalCount: number;
  countries: { name: string; slug: string; count: number }[];
  subjects: { name: string; slug: string; count: number }[];
  sources: StaticSourceSummary[];
}
